# Server configuration
server.port=8089
debug=true

# Application name
spring.application.name=weather-mcp

# MCP Server configuration
spring.ai.mcp.server.name=weather-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=ASYNC
#spring.ai.mcp.server.sse-endpoint=/mcp/sse
#spring.ai.mcp.server.sse-message-endpoint=/mcp/message

# Logging configuration
logging.level.root=INFO
logging.level.com.gox.weather=DEBUG

# Jackson configuration
spring.jackson.serialization.indent-output=true
